### ISSUE TITLE
Issue with Kubectl IBM License

### ISSUE THREAD

**Issue by aks3333** [ibm-messaging/mq-helm#10]
Hi @callumpjackson & Team
Need your help to the issue we are facing with Operator Lifecycle Manager (OLM).
we follow the  all the step via link - https://github.com/IBM/ibm-licensing-operator/blob/release-1.8/docs/Content/Install_from_scratch.md
& 
at step no 3.C  where we had given our own **namespace** value the clusterserviceversion went into **Pending** phase.

Can you please help if any other steps needs to be followed ?
 
Regards
Atul

**Comment by callumpjackson** [comment]
Hi, this issue needs to be raised in the corresponding [GitHub repository](https://github.com/IBM/ibm-licensing-operator). When you raise the issue please reference here so others can discover. 
Thanks

**Comment by aks3333** [comment]
Hi @callumpjackson 

updated the same as link below -
https://github.com/IBM/ibm-licensing-operator/issues/549#issue-1120925805

**Comment by callumpjackson** [comment]
Thanks @aks3333 I'll close off the issue here.
