### ISSUE TITLE
Do we require qmPVC volume to be in PVC?

### ISSUE THREAD

**Issue by chcshinimai** [ibm-messaging/mq-helm#105]
I'm using IBM MQ with multi-instance for a quite while. I recently notice that /mnt/mqm gets out of space. This is because web service(I think) is generating core dumps in that volume. 
I know why it's generating and this is due to my environmental setup I can't avoid. 
The question is can we use emptyDir for /mnt/mqm volume instead of a PVC? It looks like stuff under the /mnt/mqm is generate every time when it spins up. There are some error logs stored but emptyDir won't be cleaned up when a container gets restarted with some errors so the error logs should be kept. 
What's your thoughts on this or any concerns?

**Comment by vgavinash** [comment]
I dont think its permissible as emptyDir is used only for readOnlyRootFileSystem as seen in this template yaml - https://github.com/ibm-messaging/mq-helm/blob/main/charts/ibm-mq/templates/stateful-set.yaml. However I would request @callumpjackson's opinion about this.

**Comment by chcshinimai** [comment]
@vgavinash Thanks for your response. 
I modify the helm chart to have the volume with emptyDir. I have tested it with creating some messages in queues. It looks fine with emptyDir.

**Comment by callumpjackson** [comment]
Hi - we have not tested this ourselves. I do wonder if it would be a better approach to mount a new file system particularly for the web console logs, instead of generically /mnt/mqm. For instance, if you experienced an issue with the queue manager and needed to submit the logs to support they wouldn't be available in the above approach.

**Comment by chcshinimai** [comment]
@callumpjackson That is actually a good idea. That will solve our problems as well. I will keep the logs in PV and others in emptyDir or something non-PV. 
Thanks.

**Comment by vgavinash** [comment]
@chcshinimai if your prob is resolved request you to close this issue.

**Comment by callumpjackson** [comment]
Assuming resolved and closing.
