### ISSUE TITLE
Sample for VMware Tanzu Kubernetes Grid

### ISSUE THREAD

**Issue by smpby** [ibm-messaging/mq-helm#13]
Currently there are samples for deployment on OpenShift, AWS and Azure. 
Unfortunatly we only have [TKGi](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid-Integrated-Edition/index.html) on premise.

Would it be possible to provide sample charts for the TKG Kubernetes Distribution?

**Comment by callumpjackson** [comment]
Sample created [here](https://github.com/ibm-messaging/mq-helm/blob/main/samples/VMwareTanzu/README.md). Let me know if you have any difficulties.
