### ISSUE TITLE
Error while Sending the Message 

### ISSUE THREAD

**Issue by akhil-1991** [ibm-messaging/mq-helm#23]
Hi @callumpjackson 

While sending the message getting the below error. can you please try to help.
W0812 12:47:31.053301    1125 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Starting amqsphac secureapphelm
sendMessage.sh: line 27: /opt/mqm/samp/bin/amqsphac: No such file or directory
akhil1_aggarwal@cs-469377201213-default:~/mq-helm-main/samples/GoogleKubernetesEngine/test$

**Comment by callumpjackson** [comment]
Hi,
The sendMessage.sh utility depends on a MQ installation on the local machine. This can be downloaded for free from [here](https://ibm.biz/mqdevubuntu), and more detailed instructions available [here](https://developer.ibm.com/tutorials/mq-connect-app-queue-manager-ubuntu/).

**Comment by callumpjackson** [comment]
I'll close the issue for now, but feel free to re-open if you have issues.
