### ISSUE TITLE
Not Able to Login Using MQ COnsole

### ISSUE THREAD

**Issue by akhil-1991** [ibm-messaging/mq-helm#24]
Hi @callumpjackson,

I was able to launch the MQ console using GKE, but does not know what would be the user name and password for the same.
if you can help with the same where and how to recieve the username and password.

Error:
AMQ9660E: SSL key repository: password incorrect or, stash file absent or unusable. [ArithInsert1(408), CommentInsert1(MTLSQMCHL), CommentInsert2(gsk_environment_init)]

Thanks in advance.

**Comment by callumpjackson** [comment]
Hi,
The above is slightly unclear, are you asking for the default username and password for the web console? Or are you asking about the errors:
`AMQ9660E: SSL key repository: password incorrect or, stash file absent or unusable. [ArithInsert1(408), CommentInsert1(MTLSQMCHL), CommentInsert2(gsk_environment_init)]`
These are completely different problems, the first is for the web console, while the second is regarding the MQ data port and TLS configuration?

**Comment by akhil-1991** [comment]
Hi,

While launching the web console i had tried with the user name and password maintained in the secret. But got below error in the logs.

i believe second error is due to client not properly configured.?
I am new to the mq might be missing on the basic errors.

**Comment by callumpjackson** [comment]
The default web console username is `admin `and the password is `passw0rd`
You can find details of this [here ](https://github.com/ibm-messaging/mq-container/blob/master/docs/developer-config.md)and also how to customize. 
I'm not sure what secret you are referring to?

**Comment by callumpjackson** [comment]
Closing as no additional communication in 1 month
