### ISSUE TITLE
Variables for port numbers

### ISSUE THREAD

**Issue by JGrzybowski** [ibm-messaging/mq-helm#25]
Is there a reason that port numbers are not customizable in the chart? Eg. in load balancer?
If not, can I provide a pull request allowing such feature?

**Comment by callumpjackson** [comment]
I'm assuming you are suggesting that the load balancer services are changed to have a:
```
port: <loadbalancer port>
targetPort: <target container port>
```
Where the `<loadbalancer port>` can be customized within the helm chart?
If so, happy for you to create a pull request with this change, but please assure that you read and explicitly say in the pull request that you accept the [CLA](https://github.com/ibm-messaging/mq-helm/blob/main/CLA.md).

**Comment by callumpjackson** [comment]
Closing as no additional action required at this time.
