### ISSUE TITLE
is this the new repo for m

### ISSUE THREAD

**Issue by irl-segfault** [ibm-messaging/mq-helm#26]
Hello!

I'm wondering what happened to the `ibm-mqadvanced-server-dev` chart.  Is this the new replacement for that chart? I don't see that repo on Github anymore.  Wondering if going forward this is the canonical and supported Helm chart for IBM MQ on K8s.  Thanks!!

**Comment by callumpjackson** [comment]
This is the IBM MQ helm chart going forward, and the logical replacement for `ibm-mqadvanced-server-dev`. As you say the previous GitHub repo has now been removed.
