### ISSUE TITLE
Add seccompProfile type to values

### ISSUE THREAD

**Issue by andrescolodrero** [ibm-messaging/mq-helm#34]
Hi,
there is an error deploying this chart in OpenShift 4.11.25.
W0208 14:36:11.941652    1433 warnings.go:70] would violate PodSecurity "restricted:v1.24": seccompProfile (pod or container "qmgr" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

It will be excellent to have it in values.yaml

securityContext:
        seccompProfile:
          type: RuntimeDefault

**Comment by callumpjackson** [comment]
Hi - I've included this within pull request #39, with a couple of additional updates. 
Closing as completed, but re-open if you feel differently.
