### ISSUE TITLE
Howto specify replica container productID

### ISSUE THREAD

**Issue by JBarbes** [ibm-messaging/mq-helm#44]
When I build my own container using the helm chart from git, and this container is a nativeHA instance, how do I provide different productID’s in the annotations for the active instance and the 2 standby instances respectively?
I assume I need to do so, since there are different licenses for the two.

rgds
John Barbesgaard

**Comment by callumpjackson** [comment]
Hi John,
Currently the IBM License Service only tracks pods that are alive and ready to receive traffic. In the case of NativeHA only one out of the three are in this state and the remaining two are not charged. Therefore you do not need to worry about different productIDs for the active and standby instances.
