### ISSUE TITLE
Webconsole Read  Only User

### ISSUE THREAD

**Issue by inggaboluna** [ibm-messaging/mq-helm#54]
Hello,

We are trying to add an additional web console RO user  with the  role "MQWebAdminRO" we were able to added it manually under 
/mnt/mqm/data/web/installations/Installation1/servers/mqweb/ by replacing  the  file mqwebuser.xml  but the change is not persistent to a pod restart or a fail over  in native ha, we have persisten storage defined. The  following is the content of the  xml file : 

```
<?xml version="1.0" encoding="UTF-8"?>
<server>
    <featureManager>
        <feature>appSecurity-2.0</feature>
        <feature>basicAuthenticationMQ-1.0</feature>
    </featureManager>
    <enterpriseApplication id="com.ibm.mq.console">
        <application-bnd>
            <security-role name="MQWebAdmin">
                <group name="MQWebUI" realm="defaultRealm"/>
            </security-role>
            <security-role name="MQWebAdminRO">
                <group name="MQWebMessaging" realm="defaultRealm"/>
            </security-role>
        </application-bnd>
    </enterpriseApplication>
    <enterpriseApplication id="com.ibm.mq.rest">
        <application-bnd>
            <security-role name="MQWebAdmin">
                <group name="MQWebUI" realm="defaultRealm"/>
            </security-role>
            <security-role name="MQWebUser">
                <group name="MQWebMessaging" realm="defaultRealm"/>
            </security-role>
        </application-bnd>
    </enterpriseApplication>
    <basicRegistry id="basic" realm="defaultRealm">
        <user name="admin" password="${env.MQ_ADMIN_PASSWORD}"/>
        <!-- The app user will always get a default password of "passw0rd",
             even if you don't set the environment variable.
             See `webserver.go` -->
        <user name="app" password="${env.MQ_APP_PASSWORD}"/>
        <group name="MQWebUI">
            <member name="admin"/>
        </group>
        <group name="MQWebMessaging">
            <member name="app"/>
        </group>
    </basicRegistry>
    <variable name="httpHost" value="*"/>
    <variable name="managementMode" value="externallyprovisioned"/>
    <variable name="mqConsoleRemoteSupportEnabled" value="false"/>
    <variable name="mqConsoleEnableUnsafeInline" value="true"/>
    <jndiEntry jndiName="mqConsoleDefaultCCDTHostname" value="${env.MQ_CONSOLE_DEFAULT_CCDT_HOSTNAME}"/>
    <jndiEntry jndiName="mqConsoleDefaultCCDTPort" value="${env.MQ_CONSOLE_DEFAULT_CCDT_PORT}"/>
    <include location="tls.xml"/>
</server>
```

Is there a way  to add a webconsole  read only user by specifying it in the values  file  for the chart?

Regards

**Comment by arthurbarr** [comment]
The mqwebuser.xml for the MQ Advanced for Developers image is _generated_ from a template under `/etc/mqm/web`.  The templating is run every time the container starts.  So you can technically achieve what you want to do if you update the template.  Note that we are working on changing how this works in future versions of the container image.

**Comment by inggaboluna** [comment]
So then there is no way  to add a webconsole read only user by specifying it in the values file for the chart? or any other  way to add a wbconsole read only user  without having to  rebuilt the image ?

**Comment by arthurbarr** [comment]
You don't have to re-build the image, just add a layer on top.  But yes, that's currently correct.

**Comment by inggaboluna** [comment]
@arthurbarr   thanks  a lot for  your  help. We add the extra  layer  and  now we have  the  ro user for the  webconsole.

**Comment by inggaboluna** [comment]
Please let us know if any change in how this  works in the  future.

Best regards

**Comment by andrescolodrero** [comment]
@arthurbarr is there any changes here? It is fine to build our own images, but i dont to have LDAP or OIDC settings in the mqwebuser template.
It will be nice to override the template as we usually do with INI or MQ config.
