### ISSUE TITLE
Override image entrypoint

### ISSUE THREAD

**Issue by heannig** [ibm-messaging/mq-helm#55]
The mq-container image's default entrypoint is the dev-server:
`ENTRYPOINT ["runmqdevserver"]` 
(https://github.com/ibm-messaging/mq-container/blob/19d50fc15ed427c2a60e9315399f9a0d91182791/Dockerfile-server#L203)

It would be nice to be able to override the entrypoint for production use in the chart. Could you add the run-key with a variable or is there any other way to activate prod mode?

**Comment by callumpjackson** [comment]
Hi - the container image you are referring to is built using the IBM MQ Developer Edition binaries and includes the associated developer license. Its not appropriate to simply change the ENTRYPOINT of this container as the license will not match the usage. Instead you should rebuild the container using the instructions [here](https://github.com/ibm-messaging/mq-container). The same helm chart will then work, you simply change the image details to point at the container image you have created.

Closing the issue at this time, but feel free to re-open if anything is not clear.
