### ISSUE TITLE
Classic-Load balancer is getting created

### ISSUE THREAD

**Issue by Murali-Cloudbridge** [ibm-messaging/mq-helm#58]
When we deploy the solution, only classic load balancer is getting created, is there any way we can update the chart to create NLB when deploying the solution.

Whether we need to deploy aws-load-balancer controller and modify values.yaml accordingly.

**Comment by callumpjackson** [comment]
Hi Murali, 
The AWS load balancer configuration, including if classic or NLB, is controlled by annotations on the load balancer service. This can already be customized using the route.loadBalancer.annotations property. You will see that we configure a separate annotation in the AWS sample [here](https://github.com/ibm-messaging/mq-helm/blob/024f9300eb10755637340177c39fdf82a0296d5a/samples/AWSEKS/deploy/secureapp_nativeha.yaml#L63), and can use a similar mechanism to change to an NLB. 

Closing as resolved - feel free to re-open as needed.
