### ISSUE TITLE
Addition of existing Security groups to EKS cluster

### ISSUE THREAD

**Issue by Murali-Cloudbridge** [ibm-messaging/mq-helm#59]
We have modified the stacks according to our requirements to launch worker nodes in private subnets and include boot nodes. Now, we are facing issues in the boot node accessing the EKS cluster API endpoint. We have fixed this by manually adding the security group to EKS by allowing the entire VPC CIDR or allowing the IP of the boot node alone. We need to add this security group within eksctl commands as shown below.

We tried by adding  below values

clusterSecurityGroup="sg-1234567". but failed with association. 

Resources:
  BootNodeProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RoleName
      Path: /
  BootNode:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          Required:
            - StackPropertiesFile
        StackPropertiesFile:
          commands:
            01_create_opt_ibm:
              command: mkdir -p /opt/ibm
              test: test ! -d /opt/ibm
          files:
            /opt/ibm/cluster.yaml:
              mode: '000755'
              owner: root
              group: root
              content:
                !Sub
                - |
                  apiVersion: eksctl.io/v1alpha5
                  kind: ClusterConfig
                  metadata:
                    name: ${ClusterName}
                    region: ${AWS::Region}
                  vpc:
                    subnets:  
                      private:
                        ${AZ1}: { id: ${PrivateSubnet1ID} }
                        ${AZ2}: { id: ${PrivateSubnet2ID} }
                        ${AZ3}: { id: ${PrivateSubnet3ID} }
                    clusterEndpoints:
                      publicAccess:  true
                      privateAccess: true
                  managedNodeGroups:
                    - name: ng-1-workers
                      instanceType: m5.large
                      desiredCapacity: 3
                      privateNetworking: true
                - AZ1: !Ref AvailabilityZone1
                  AZ2: !Ref AvailabilityZone2
                  AZ3: !Ref AvailabilityZone3
                  PrivateSubnet1ID: !Ref PrivateSubnet1ID
                  PrivateSubnet2ID: !Ref PrivateSubnet2ID
                  PrivateSubnet3ID: !Ref PrivateSubnet3ID
                  ClusterName: !Ref EKSClusterName

Thanks,
Murali

**Comment by callumpjackson** [comment]
The above issue does not appear to be a question/problem relating to the MQ Helm chart. It sounds like you need assistance from AWS to configure you EKS cluster correctly.

**Comment by callumpjackson** [comment]
Closing as unrelated to MQ Helm and no update.
