### ISSUE TITLE
Changing MQ queue manager name and how to set privileges for containers running in pod. 

### ISSUE THREAD

**Issue by Murali-Cloudbridge** [ibm-messaging/mq-helm#61]
1. How to change the default MQ queue manager name from "secureapphelm" to something else. We should make this configurable instead of hardcoding it.

2. How to install any packages that we might need on the container itself. For instance, we might want to install git or jq command line tool to run some configuration scripts. Do we have access to the root user on the container itself to do this?

3. The current solution uses IBM MQ Advanced for Developer's container image. How do we change it to use the IBM MQ Advanced production image? Does this require a complete cluster rebuild or can the image be switched without the rebuild?

**Comment by callumpjackson** [comment]
Hi Murali, please find the answers to your questions below:

1. The queue manager name can be customized using a helm chart property. These are all documented [here](https://github.com/ibm-messaging/mq-helm/tree/main/charts/ibm-mq#configuration), and the one required is `queueManager.name`. 
2. This is a question for the [mq-container GitHub](https://github.com/ibm-messaging/mq-container). You can rebuild the image, and then layer in the tools you require using standard container layers approach.
3. This is a question for the [mq-container GitHub](https://github.com/ibm-messaging/mq-container). This repo includes documentation on building the production image. You then reference this new image using the `image.repository` and `image.tag` helm chart properties.
