### ISSUE TITLE
is the Helm Chart production grade?

### ISSUE THREAD

**Issue by andrescolodrero** [ibm-messaging/mq-helm#62]
Hi,

is it the Helm chart a supported way to run IBM MQ on production or we should stay with Operators?
While operator can bring some benefits, it tight us to an specific version of OpenShift (and even number 4.10, 4.12) and breaks our intention of keep the cluster upgraded very often.
Question come because i usually see in IBM docs that Operator is the prefered way.

But i guess, CLoud Pak / entitlement keys are mandatory even if im using helm chart.

**Comment by callumpjackson** [comment]
Hi Andrea,
The MQ operator is the suggested deployment mechanism for Red Hat OpenShift as it provides greater support for our customers. By using the operator they have access to the IBM supplied and supported container images, as well as the supported operator. The MQ operator also provides additional features (such as rolling upgrades) that are not available in the helm chart and instead provided as separate sample scripts. 

If you decide to use the MQ Helm chart customers are currently responsible for building their licensed container images, based on the guidance available in the[ mq-containers](https://github.com/ibm-messaging/mq-container) repo. Questions regarding the MQ Helm chart can be raised in this repo but again currently they are not serviced by IBM support.

**Comment by callumpjackson** [comment]
Closing unless there are any additional questions.

**Comment by andrescolodrero** [comment]
Thanks,
@callumpjackson 
I have been testing the operator and found that i need to install many operator in Openshift to make it work (finally, found the way to dont use Cloud Pak IAM for the web console).  
CP4I, at minimum, required on-way TLS, and i have many clients that will need to be update in a local network because of this (and test), so i will still need some clients to use simple MQ Port. 
Building our own images shouldnt be an issue, but it will be supported by IBM our installation? (i dont mean the Helm Chart)?

**Comment by callumpjackson** [comment]
If you decide to build your own MQ container image. IBM support will process issues reported in the MQ product binaries. For instance, if you reported an issue with a MQ channel, they would investigate this. If you raised an issue regarding the container or helm deployment code this would need to be raised within the corresponding GitHub repo. Hope this helps.
