### ISSUE TITLE
what is the process to update the application license?

### ISSUE THREAD

**Issue by arvind-cb** [ibm-messaging/mq-helm#63]
Currently we are using developer license and soon would be updating the license. 
Could you please let us know if updating the license would require cluster rebuild?
What is the process to update the license without having any down time?

**Comment by callumpjackson** [comment]
Hi - from the description you are using the IBM MQ Advanced Developer Edition container image. When moving to a licensed MQ edition you should rebuild the container using the instructions [here](https://github.com/ibm-messaging/mq-container). The same helm chart will then work, you simply change the image details to point at the container image you have created.

At the same time you will need to update the [license annotations](https://www.ibm.com/docs/en/ibm-mq/9.3?topic=sbyomqmci-license-annotations-when-building-your-own-mq-container-image) and install the [IBM License service](https://github.com/IBM/ibm-licensing-operator#ibm-licensing-operator-for-deploying-license-service-without-an-ibm-cloud-pak). 

Closing the issue at this time, but feel free to re-open if anything is not clear.
