### ISSUE TITLE
Add loadBalancerIP to service-loadbalancer template

### ISSUE THREAD

**Issue by jseigman-apex** [ibm-messaging/mq-helm#64]
We have a use case where we are using an internal static IP for our ibm-mq loadbalancer. Setting this requires a `loadBalancerIP` parameter along with an annotation. The current service-loadbalancer template does not have this and others may benefit, so could it be added or would you accept a PR with the following addition?
 
```
spec:
  loadBalancerIP: {{ .Values.route.loadBalancer.loadBalancerIP }}
``` 

Thank you!

**Comment by callumpjackson** [comment]
Thanks for raising the issue. In general, we are open to feature enhancements and encourage pull requests from the community. It is useful that you raised the issue in this case as we do have some questions on the .spec.loadBalancerIP field. Based on the Kubernetes [documentation](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer) this field was deprecated in v1.24, which is 18 months old (released in May 2022). As the most recent release is v1.28 we are apprehensive of including a field which could be removed from the Kubernetes API. Load balancer annotations are already provided as an alternative, which is the suggested approach mentioned within the Kubernetes documentation. For interest what load balancer is requiring you to specify loadBalancerIP. As always we continue to be open minded, but have to be sensitive of the ongoing maintenance.

**Comment by jseigman-apex** [comment]
I would gladly use an annotation but afaik GKE does not have one to replace it yet. Please let me know if there is one. 
I understand not wanting to add a deprecated field, so if we can't get this with the annotation, we will explore other ways of setting up the load balancer service. Thank you!
