### ISSUE TITLE
Queue's default persistance in native ha mode

### ISSUE THREAD

**Issue by lavalex** [ibm-messaging/mq-helm#68]
Hello,

I've noticed a strange thing. When I modify DEFPSIST of one of the pre created queues, for example DEV.QUEUE.1, after the failover it is set to NO again ... But if I create a new queue, perform couple of failovers, then modify DEFPSIST to YES and perform failover again, it's kept (as expected).

what is different about pre created queues in the container?

Thank you

**Comment by callumpjackson** [comment]
This is really a question for the [mq-containers](https://github.com/ibm-messaging/mq-container) repository and not mq-helm. The DEV.QUEUE.1 is created by a MQSC file embedded within the image. You can see the source of the file [here](https://github.com/ibm-messaging/mq-container/blob/403e4f045d681ba416b4c7da466e499ec83b0396/incubating/mqadvanced-server-dev/10-dev.mqsc.tpl#L17). Every time the container is started it will re-load this MQSC file, and over-write your manual changes. If you have further questions please ask them in the mq-containers repository.
