### ISSUE TITLE
Web Console is not available for mq advanced server container

### ISSUE THREAD

**Issue by scannerscan** [ibm-messaging/mq-helm#72]
Hi Team, my deployment works fine with mq advanced developer container (9.3.4.0-r1). That includes Web Console. when I changed the container to mq advanced server (cp.icr.io/cp/ibm-mqadvanced-server:9.3.4.0-r1), the web console did not start (no corresponding logs). Could you please advise if I am missing something?

**Comment by callumpjackson** [comment]
There is a difference in the default behavior between the developer and license container images. The developer image has this enabled by default, while the licensed version has it disabled. To enable in both cases use:
`web.enable`

There is a second related difference that you may hit, the web console authentication is not configured. In the latest helm chart (8.0.0) in combination with 9.3.4 you can specify the web configuration within a configMap or secret.

**Comment by scannerscan** [comment]
@callumpjackson the info is very much appreciated!! do you have a config example for the web.manualConfig ?

**Comment by scannerscan** [comment]
@callumpjackson I got it now. The key name must be mqwebuser.xml.
`web:
  enable: true

  manualConfig:
    configMap:
      name: mqConfigMap
      items:
        - mqwebuser.xml`

**Comment by callumpjackson** [comment]
Great - I'll close off the issue
