### ISSUE TITLE
How multiple trust store certificates are recognised?

### ISSUE THREAD

**Issue by scannerscan** [ibm-messaging/mq-helm#76]
Hi, I am trying to understand how the multiple truststore certificates are getting recognised.
Based on the mq containers docs from https://github.com/ibm-messaging/mq-container/blob/master/docs/usage.md , 
the way they designed it was the following:
- /etc/mqm/pki/trust/<index> - for certificates with only the public key

Example:
- /etc/mqm/pki/trust/0/tls.crt
- /etc/mqm/pki/trust/1/tls.crt

As per the helm value file and the helm documentation, it is: 
pki:
  trust:
    - name: default
      secret:
        secretName: appsecret
        items:
          - app.crt
          
If I add multiple items (.crt files), 
pki:
  trust:
    - name: default
      secret:
        secretName: appsecret
        items:
          - app1.crt
          - app2.crt
          - app3.crt

they will be placed under a single index - '0' in the MQ container file system, say, 
/etc/mqm/pki/trust/0/app1.crt
/etc/mqm/pki/trust/0/app2.crt
/etc/mqm/pki/trust/0/app3.crt

Does that approach still work or MQ is designed to have something like that?
/etc/mqm/pki/trust/0/app1.crt
/etc/mqm/pki/trust/1/app2.crt
/etc/mqm/pki/trust/2/app3.crt

**Comment by scannerscan** [comment]
> Looking at the container code both options should work, have you seen an issue?

have not tested that scenario yet, just picked up the difference and wanted to confirm if there is an issue or not

**Comment by callumpjackson** [comment]
I think everything is fine. For your awareness, you could also have multiple secrets with a single item and this would map to the other mechanism. Closing issue unless there is a problem discussed.
