### ISSUE TITLE
How to preserve client IP address when using Nginx LB

### ISSUE THREAD

**Issue by xeberth** [ibm-messaging/mq-helm#77]
![image_2024-03-14_123510423](https://github.com/ibm-messaging/mq-helm/assets/54719682/b5bf04ba-d5d7-430c-a80b-5e3634ef9930)

Hi we are testing this deployment, but we identified that client IP address are not preserved even if we enabled ProxyProtocol in NGINX Controller.

NGINX configmap settings:

data:
  allow-snippet-annotations: "true"
  compute-full-forwarded-for: "true"
  use-forwarded-headers: "true"
  use-proxy-protocol: "true"

NGINX LoadBalancer Service:

externalTrafficPolicy: Local
allocateLoadBalancerNodePorts: false

QMGR Service settings:

metadata:
  name: qmtest-ibm-mq-qm
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  type: NodePort

This configuration works to Preserve Client IP Address in other Kubernetes based applications that we have, but only on MQ Container client IP preservation not working and "DISPLAY CONN(*) CHANNEL CONNAME" still showing the K8S LoadBalancer IPs in CONNAME section as can see in the image.

Have some example of how to configure MQ services to Preserve IP Clients when connecting using a LoadBalancer ?

**Comment by callumpjackson** [comment]
Hi Heber - to preserve the client IP, IBM MQ needs to support the proxy protocol. This is NOT related to the helm chart, but the underlying IBM MQ code base. This is NOT currently supported and there is a request for enhancement already available [here](https://integration-development.ideas.ibm.com/ideas/MESNS-I-335). I would encourage yourself and anyone else who feels this is a required feature to vote for the enhancement.

**Comment by callumpjackson** [comment]
Closing as this is an RFE for the MQ code base, not the helm chart.
