### ISSUE TITLE
Unable to configure mq multi instance on Azure AKS

### ISSUE THREAD

**Issue by VD099** [ibm-messaging/mq-helm#78]
Hi Team,

I'm trying to spin up multi-instance mq in AKS, when I try to run the install.sh script the pod is not coming up and in events it is showing up unable to mount or attach volumes. But when I check the relevant PVCs the status is showing as bound. not sure what exactly is causing this error. Looking for assistance on this issue.

Thanks in Advance

**Pod Events:**

Unable to attach or mount volumes: unmounted volumes=[qm data log], unattached volumes=[default mqsc-cm-helmsecure ini-cm-helmsecure qm data log kube-api-access-sg6pr trust0]: timed out waiting for the condition
 
Unable to attach or mount volumes: unmounted volumes=[data log qm], unattached volumes=[data log kube-api-access-sg6pr trust0 default mqsc-cm-helmsecure ini-cm-helmsecure qm]: timed out waiting for the condition
 
Unable to attach or mount volumes: unmounted volumes=[qm data log], unattached volumes=[qm data log kube-api-access-sg6pr trust0 default mqsc-cm-helmsecure ini-cm-helmsecure]: timed out waiting for the condition
 
MountVolume.MountDevice failed for volume "pvc-68153b01-3341-4b98-a9b3-97da5f92fea1" : rpc error: code = Internal desc = volume(rg-aksnodes-rbs-dip-nonprd-e2-01#f999eab35c0084287808317#pvcn-68153b01-3341-4b98-a9b3-97da5f92fea1###multi-mq) mount f999eab35c0084287808317.file.core.windows.net:/f999eab35c0084287808317/pvcn-68153b01-3341-4b98-a9b3-97da5f92fea1 on /var/lib/kubelet/plugins/kubernetes.io/csi/file.csi.azure.com/4db2af01f85980738f013d75431e57c42e780c51163016cafe11251f668ca304/globalmount failed with mount failed: exit status 32 Mounting command: mount Mounting arguments: -t nfs -o rw,vers=4,minorversion=1,sec=sys f999eab35c0084287808317.file.core.windows.net:/f999eab35c0084287808317/pvcn-68153b01-3341-4b98-a9b3-97da5f92fea1 /var/lib/kubelet/plugins/kubernetes.io/csi/file.csi.azure.com/4db2af01f85980738f013d75431e57c42e780c51163016cafe11251f668ca304/globalmount Output: mount.nfs: access denied by server while mounting f999eab35c0084287808317.file.core.windows.net:/f999eab35c0084287808317/pvcn-68153b01-3341-4b98-a9b3-97da5f92fea1
 
(combined from similar events): Unable to attach or mount volumes: unmounted volumes=[log qm data], unattached volumes=[log kube-api-access-sg6pr trust0 default mqsc-cm-helmsecure ini-cm-helmsecure qm data]: timed out waiting for the condition

**Comment by callumpjackson** [comment]
Have you tried the [multi-instance](https://github.com/ibm-messaging/mq-helm/tree/main/samples/AzureAKSMultiInstance) sample. Looking at the error message it appears the wrong mount options are being used. The sample creates a new storage class with the correct mount options. It’s worth saying that most people use NativeHA as it avoids the storage issues, and generally provides better performance.

**Comment by VD099** [comment]
Hi @callumpjackson

Yes, we have tried the multi-instance scripts which is throwing the volume mount error,

Thanks in Advance.

**Comment by callumpjackson** [comment]
Sorry for the delayed follow-up, did you manage to resolve this issue?

**Comment by callumpjackson** [comment]
Close due to inactivity - feel free to re-open if applicable.
