### ISSUE TITLE
Routing IBM MQ using Kong Ingress Service

### ISSUE THREAD

**Issue by Rockyjr-git** [ibm-messaging/mq-helm#90]
![Screenshot 2024-06-26 120025](https://github.com/ibm-messaging/mq-helm/assets/85946434/2dde54ff-fd7f-4187-8a21-a91c2e53660d)
![kong-ing](https://github.com/ibm-messaging/mq-helm/assets/85946434/6a3152d2-56ee-467c-95ba-78e279c8c826)
Please help me with a kong ingress service yaml for the IBM MQ service. I have tried using attached ingress yamls but ended with an error. Also Please help me with an annotations, so that i can use the custom path like /foo instead of default path /

**Comment by callumpjackson** [comment]
I'm assuming you are using the [Kong Ingress Controller](https://docs.konghq.com/kubernetes-ingress-controller/latest/). I understand this is a API Gateway. I am confused why you are putting this in-front of the MQ web console. Do you have any additional information on the use case?

**Comment by callumpjackson** [comment]
Closing due to no response - feel free to re-open as needed.
