### ISSUE TITLE
TS016677155 -- we are trying to create a qmgr with LogFilePages=65535 and getting INI error as below(same reported in the PMR)

### ISSUE THREAD

**Issue by karthik-mangu** [ibm-messaging/mq-helm#93]
error : 
│ 2024-07-08T18:46:23.628Z AMQ5778E: Automatic configuration of INI files attempted to update a restricted value. [CommentInsert1(Log), CommentInsert2(LogType), CommentInsert3(Replicated)]                                          │

│ 2024-07-08T18:46:23.628Z AMQ5776E: Auto configuration INI definitions contain invalid syntax or illegal attributes. [CommentInsert1(INI)]

we are using same approach as this repository to create QMGR on AWS EKS.

**Please suggest us on how to create qmgr with below ini.** 

Log:
   LogPrimaryFiles=12
   LogSecondaryFiles=2
   LogFilePages=65535 
   LogType=REPLICATED
   LogBufferPages=0
   LogWriteIntegrity=TripleWrite
   LogManagement=Automatic
   
 NOTE: we were able to update primary and secondary files  value once the qmgr is up and running(editing the configmap) and i  know we cannot touch the "LogFilePages" once QMGR is created.

**Comment by arthurbarr** [comment]
In the error message, it points out the problematic value: "Replicated".  You can't set the `LogType` in this way — Native HA is configured using different Native HA INI settings, and those are in turn configured automatically by environment variables passed to the container.  The Helm chart sets those environment variables, so you can't set the `LogType` directly yourself.

**Comment by karthik-mangu** [comment]
how can we change environment variables?
do you have any example ?

**Comment by karthik-mangu** [comment]
i was able to change it by adding below :

          - name: MQ_QMGR_LOG_FILE_PAGES
            value: "65535"
