### ISSUE TITLE
AD Integration Web Console - helm chart not applying changes

### ISSUE THREAD

**Issue by aheyers** [ibm-messaging/mq-helm#94]
We are trying to integrate the web console with Active Directory but encountering issues. I checked the path /var/mqm/web/installations/Installation1/servers/mqweb/ but there is no change in configuration. 

We have created below config map and gave its reference in IBM MQ helm chart. 

We defined this in the values.yaml as in the example.

values.yaml

web:
  enabled: true
  manualConfig:
    configMap:
      name: mywebconfig
      items:
      - mqwebuser.xml

And added a configmap.

mywebconfig.yaml

kind: ConfigMap
apiVersion: v1
metadata:
  name: mywebconfig
data:
  mqwebuser.xml: |-
 <?xml version="1.0" encoding="UTF-8"?>
    <server>
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            

            

        
        <featureManager>
            <feature>appSecurity-2.0</feature>
            <feature>ldapRegistry-3.0</feature>
            <feature>basicAuthenticationMQ-1.0</feature>
        </featureManager>

        
        <enterpriseApplication id="com.ibm.mq.console">
            <application-bnd>
                <security-role name="MQWebAdmin">
                    <group name="CN=somegroup,OU=Application,OU=Groups,OU=Common,DC=domain,DC=company,DC=com" realm="MyOrganizationRealm"/>
                </security-role>
                <security-role name="MQWebUser">
                            <group name="CN=somegroup,OU=Application,OU=Groups,OU=Common,DC=domain,DC=company,DC=com" realm="MyOrganizationRealm"/>

                </security-role>
            </application-bnd>
        </enterpriseApplication>

        
        
        
        
        <ldapRegistry id="ldap"
            realm="MyOrganizationRealm"
            host="somehostname.company.com"
            port="636"
            ignoreCase="true"
            certificateMapMode="EXACT_DN"
            bindDN="CN=serviceaccount,OU=Acconts,OU=Common,DC=domain,DC=company,DC=com" 
            bindPassword="XXXXXXXXXXXXXXXXXXXX" 
            baseDN="OU=Common,DC=domain,DC=company,DC=com"
            ldapType="Microsoft Active Directory"
            sslEnabled="true"
            sslRef="thisSSLConfig">
            <activedFilters
                userFilter="(&amp;(sAMAccountName=%v)(objectcategory=user))"
                groupFilter="(&amp;(cn=%v)(objectcategory=group))" 
                userIdMap="user:sAMAccountName" 
                groupIdMap="*:cn" 
                groupMemberIdMap="memberOf:member" >
            </activedFilters>
            </ldapRegistry>

        
        <variable name="httpsPort" value="9443"/>

        
        <variable name="httpHost" value="*"/>

        
        

        
        <sslDefault sslRef="mqDefaultSSLConfig"/>

        
        

        
        

        
        <include location="tls.xml"/>
    </server>

So my question is if the file somewhere else or is there some missing step to apply changes?
What is the correct configuration needed to successfully integrate the web console with AD?

**Comment by callumpjackson** [comment]
Sorry for the delayed response. Can you verify if the configuration file is successfully mounted into the container here: /etc/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml

Also could you confirm the MQ container level being used?

**Comment by callumpjackson** [comment]
Closing - please re-open as needed.
