### ISSUE TITLE
Failover Test Fails in Native HA mode

### ISSUE THREAD

**Issue by uaw013** [ibm-messaging/mq-helm#95]
We are testing the Native High Availability mechanism using SOAP UI via our Gateway to IBM MQ.

We simulate 18 applications that send messages to the IBM MQ in a production-like situation. In SOAP UI, we created a simple test with the following configuration:

Threads: 18
Limit: 300 seconds
Test delay: 1000 ms
Random: 0.5
When we start the test without any restarts, everything works well. However, when we start the test and bring the active node down, we immediately receive the following error:

`WARNING 680 com.l7tech.external.assertions.mqnative.server.ServerMqNativeRoutingAssertion: At least 10 connections failed trying to connect to MQ.  
MQ server is not available.  Falsifying assertion.
com.ibm.mq.MQException: MQJE001: Completion Code '2', Reason '2538'.
at com.ibm.mq.MQManagedConnectionJ11.<init>(MQManagedConnectionJ11.java:255)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2538;AMQ9204: 
Connection to host 'xx.xx.xx.xx(1414)' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2538;AMQ9213: A communications error for 'TCP' occurred. [1=java.net.SocketException[Connection reset by peer (connect failed)],3=connnectUsingLocalAddress,4=TCP,5=Socket.connect]],3=xx.xx.xx.xx(1414),5=RemoteTCPConnection.connnectUsingLocalAddress]
at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:2302)
`
All messages fail, and it takes between 5 to 15 seconds before one of the replica nodes becomes the active one.

Has anyone tested the failover, and does it work?

**Comment by uaw013** [comment]
@Arthur Barr please can you help us?

update: with max 9 threads everything works well

**Comment by arthurbarr** [comment]
You say "it takes between 5 to 15 seconds before one of the replica nodes becomes the active one", which sounds like it successfully fails-over to the replica in between 5 and 15 seconds.  See https://www.ibm.com/docs/en/ibm-mq/9.4?topic=planning-high-availability-mq-in-containers for a discussion of some of the factors involved in tuning that fail-over time (it will never be zero).

**Comment by uaw013** [comment]
Hello Arthur,

Thank you for your response.

The goal is not to bring the failover to zero. Failover works well with 9 threads. However, the issue arises when we start more than 9 threads—the failover doesn't happen. It seems like there might be a limitation on the number of connections or applications that can connect with MQ.

**Comment by arthurbarr** [comment]
I wonder if this might be down to your application logic.  The error message from your application says "At least 10 connections failed trying to connect to MQ", so if that indicates it's giving up after ten threads, then it seems like something you'd need to change if you want to use more threads than that (all threads will lose connection if they're connected to the same queue manager).

As an aside, I spoke with the Native HA team about the 15 second take-over, and they said that there was an issue where MQ zeroes the content of the log extents for a replica that takes over from another instance. MQ 9.4.0.0 fixes that so it's much quicker, so it could be worth you upgrading if you haven't already.

**Comment by uaw013** [comment]
Do you mean we need to check the configuration on the sender application? The error message "Connection reset by peer" indicates that MQ closed the connection. Is this correct?

We are already using tag: 9.4.0.0-r1.

**Comment by arthurbarr** [comment]
Yes, "connection reset by peer" probably indicates that MQ, or its hosting network stack, closed the connection.  I think you'd expect that when you bring the active node down.  I think the problem is how your application code is reacting to that failure.  The error message says that _your application_ has decided that ten lost connections is too many, so may have given up.

IBM MQ does not have a limit of nine connected clients — it can handle thousands of connected clients, all of which could reconnect to the new active when it recovers.  There is a default value in the queue manager for a maximum of 100 active channels, but that can be increased.  I do not believe you are seeing any limitation in the queue manager, but rather in your own application logic.
