### ISSUE TITLE
how to update the license

### ISSUE THREAD

**Issue by uaw013** [ibm-messaging/mq-helm#96]
We are currently using the IBM MQ Helm Chart with the IBM MQ Advanced Developer Edition container image and license (icr.io/ibm-messaging/mq:9.4.0.0-r). The HA configuration works well, so we want to update the license to the IBM MQ Advanced test license before moving to production. We have downloaded IBM MQ 9.4 Trial from [IBM's website](https://www.ibm.com/resources/mrs/assets/packageList?source=ibmmqtrial&lang=en_US).

Do we need to follow the steps described [here ](https://github.com/ibm-messaging/mq-container/blob/master/docs/building.md#building-a-production-image)to update the license? Is it correct that the only prerequisites are Docker and GNU Make, and nothing else?

If yes, we encountered some errors when running this command:

Command:
`MQ_ARCHIVE=9.4.0.0-IBM-MQTRIAL-LinuxX64.tar.gz MQ_VERSION=9.4.0.0 make build-advancedserver`

Error:
```
Step 23/65 : RUN go build -ldflags "-X \"main.ImageCreated=$(date --iso-8601=seconds)\" -X \"main.ImageRevision=$IMAGE_REVISION\" -X \"main.ImageSource=$IMAGE_SOURCE\" -X \"main.ImageTag=$IMAGE_TAG\"" ./cmd/runmqserver/ && go build ./cmd/chkmqready/ && go build ./cmd/chkmqhealthy/ && go build ./cmd/chkmqstarted/ && go build ./cmd/runmqdevserver/ && go test -v ./cmd/runmqdevserver/... && go test -v ./cmd/runmqserver/ && go test -v ./cmd/chkmqready/ && go test -v ./cmd/chkmqhealthy/ && go test -v ./cmd/chkmqstarted/ && go test -v ./pkg/... && go test -v ./internal/... && go vet ./cmd/... ./internal/...
---> Running in 25685419a1b6
# github.com/ibm-messaging/mq-golang/ibmmq
vendor/github.com/ibm-messaging/mq-golang/ibmmq/mqi.go:57:10: fatal error: cmqc.h: No such file or directory
   57 | #include <cmqc.h>
      |          ^~~~~~~~
```

If not, could you please provide us with the correct procedure?

**Comment by vgavinash** [comment]
@uaw013 hi there, your inputs are bit confusing. 

As per my understanding. you are already using IBM MQ Helm Chart implementation. Then you are not supposed to use the `ibm-messaging/mq-container` repo's code. You must be using the `ibm-messaging/mq-helm`'s code instead. i.e., this does not hold good - https://github.com/ibm-messaging/mq-container/blob/master/docs/building.md#building-a-production-image in your case. 

And one more observation is, if at all you have decided to use the code of `ibm-messaging/mq-container`, I can see that you are using `9.4.0.0-IBM-MQTRIAL-LinuxX64.tar.gz` image. Instead try the steps provided here - https://www.ibm.com/docs/en/ibm-mq/9.4?topic=reference-mq-advanced-developers-container-image, which uses a developer image for building the mq-container image. 

Thanks,
Avinash

**Comment by vgavinash** [comment]
Cc: @callumpjackson

**Comment by vgavinash** [comment]
`make build-devserver` will be the command to be used. There is no trial image for `mq-container` enablement code.

**Comment by uaw013** [comment]
@vgavinash, Thank you for your response.

We need to switch from the developer license to the 30-day trial license. Could you please guide us on how to do this?

 The process isn't clear, which is why I searched through the issues and found [this one](https://github.com/ibm-messaging/mq-helm/issues/63). I followed the steps to build an image as outlined on the [build page](https://github.com/ibm-messaging/mq-container/blob/master/docs/building.md), specifically using the "Building a production image" option.

Currently, we are using the IBM MQ Helm Chart implementation, which, as I understand, is built from the developer image that includes the developer license. We want to switch to the 30-day trial license (9.4.0.0-IBM-MQTRIAL-LinuxX64.tar.gz) provided by SoftwareOne.nl before moving to production.

I hope this clarifies our situation.

Thank you for your assistance.

**Comment by arthurbarr** [comment]
IBM does not produce a container image for use with the trial license, I'm afraid.  I don't think it's readily possible to build your own container either, because the [sample container image](https://github.com/ibm-messaging/mq-container) only works with the special "no-install" version of MQ, which I don't think is available with the trial license.  i.e. the tar.gz file you have downloaded probably contains RPMs, but the sample container image does not get installed that way.

**Comment by uaw013** [comment]
@arthurbarr, Thank you for your response.

I’ve sent your response to SoftwareOne.nl to obtain the correct license.

Could you please outline the general steps to change the developer license of IBM MQ NativeHA on Kubernetes?

**Comment by arthurbarr** [comment]
I don't think it's possible to use the MQ trial license with a container at this time.

I'm not sure what you mean about changing the developer license.  The license is associated with the code installed in the container.  You should be able to take the data from a queue manager deployed with the MQ Advanced for Developers license, and run that with a licensed MQ Advanced container, just by upgrading the Helm installation with a different image.

**Comment by uaw013** [comment]
@arthurbarr, 

What I mean about "changing the developer license" is, what are the steps if I want to use this Helm Chart (https://github.com/ibm-messaging/mq-helm) in production? Where can I found the documentation.

**Comment by arthurbarr** [comment]
The Helm chart defaults to using a public image from icr.io.  If you want to use MQ in production, then you need to build your own container image.  You can see instructions for doing that here: https://github.com/ibm-messaging/mq-container/blob/master/docs/building.md#building-a-production-image

**Comment by callumpjackson** [comment]
Closing as the issue appears to be resolved. Feel free to reopen with a new question if this is incorrect.
